[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
serde.workspace = true
serde_json.workspace = true

chrono = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }
uuid = { version = "1.11", features = ["v4"], optional = true }

[features]
server = ["dioxus/server", "dep:uuid"]
