[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

# For WASM target (web)
[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = "0.3"
api = { workspace = true }

# For server target (when building server)
[target.'cfg(not(target_family = "wasm"))'.dependencies]
api = { workspace = true }

[features]
web = ["dioxus/web"]
server = ["dioxus/server"]
